version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: pokedex
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret

  keycloak:
    container_name: keycloak_dev
    image: quay.io/keycloak/keycloak:20.0.2
    command: "start --import-realm"
    volumes:
      - './keycloak/realms:/opt/keycloak/data/import'
      - './keycloak/export:/opt/keycloak/data/export'
    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pokedex
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: secret
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080/auth

networks:
  backend: